---
abstract: 'Run something before a route execute'
author:
  - 'Michael Vu <email@michael.vu>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.133380'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer-Plugin-BeforeRoute
requires:
  Dancer: 0
  Test::More: 0
version: 0.2
